src/main/java/com/gongkademy/domain/community/controller/BoardController.java
src/main/java/com/gongkademy/domain/community/controller/CommentController.java
src/main/java/com/gongkademy/domain/community/controller/CommentLikeController.java
src/main/java/com/gongkademy/domain/community/controller/PickController.java
src/main/java/com/gongkademy/domain/community/dto/request/BoardRequestDTO.java
src/main/java/com/gongkademy/domain/community/dto/request/CommentLikeRequestDTO.java
src/main/java/com/gongkademy/domain/community/dto/request/CommentRequestDTO.java
src/main/java/com/gongkademy/domain/community/dto/request/PickRequestDTO.java
src/main/java/com/gongkademy/domain/community/dto/response/BoardResponseDTO.java
src/main/java/com/gongkademy/domain/community/dto/response/CommentLikeResponseDTO.java
src/main/java/com/gongkademy/domain/community/dto/response/CommentResponseDTO.java
src/main/java/com/gongkademy/domain/community/dto/response/PickResponseDTO.java
src/main/java/com/gongkademy/domain/community/repository/BoardRepository.java
src/main/java/com/gongkademy/domain/community/repository/CommentLikeRepository.java
src/main/java/com/gongkademy/domain/community/repository/CommentRepository.java
src/main/java/com/gongkademy/domain/community/repository/PickRepository.java
src/main/java/com/gongkademy/domain/community/repository/QnaBoardRepository.java
src/main/java/com/gongkademy/domain/community/service/BoardService.java
src/main/java/com/gongkademy/domain/community/service/BoardServiceImpl.java
src/main/java/com/gongkademy/domain/community/service/CommentLikeService.java
src/main/java/com/gongkademy/domain/community/service/CommentLikeServiceImpl.java
src/main/java/com/gongkademy/domain/community/service/CommentService.java
src/main/java/com/gongkademy/domain/community/service/CommentServiceImpl.java
src/main/java/com/gongkademy/domain/community/service/PickService.java
src/main/java/com/gongkademy/domain/community/service/PickServiceImpl.java
src/main/java/com/gongkademy/domain/community/service/QnaBoardService.java

- resolve #19 bug 패키지 수정으로 인한 import문제
- 이번 PR에서 작업한 내용을 설명해주세요(이미지 첨부 가능)
패키지와 import 일치하도록 작업 완료

19 bug 패키지 수정으로 인한 import문제

---

build.gradle
src/main/resources/application.properties

- [FEAT] Oauth 관련 설정
[#23](https://github.com/Gongkademy/Gongkademy_Service_Back/issues/23)
- build.gradle에 oauth 관련 설정 추가
-  application.properties에 google oauth 관련 설정 추가
- application-local.properties에 google oauth 관련 설정 추가

feat: OAuth 관련 설정

---

src/main/java/com/gongkademy/domain/community/controller/QuestionController.java
src/main/java/com/gongkademy/domain/community/dto/request/ImageRequestDto.java
src/main/java/com/gongkademy/domain/community/dto/request/QnaBoardRequestDto.java
src/main/java/com/gongkademy/domain/community/dto/response/ImageResponseDto.java
src/main/java/com/gongkademy/domain/community/dto/response/QnaBoardResponseDto.java
src/main/java/com/gongkademy/domain/community/entity/board/QnaBoard.java
src/main/java/com/gongkademy/domain/community/repository/QnaBoardRepository.java
src/main/java/com/gongkademy/domain/community/service/QnaBoardService.java
src/main/java/com/gongkademy/domain/community/service/QnaBoardServiceImpl.java
src/test/java/com/gongkademy/repository/QnaBoardRepositoryTest.java

- resolve #22
- QnaBoard에 대한 CRUD 작업을 진행하였습니다.
- 이에 대한 Test 작업 진행해 보았습니다.

Feat: QnaBoard CRUD 작업 진행

---

src/main/java/com/gongkademy/domain/community/controller/BoardController.java
src/main/java/com/gongkademy/domain/community/dto/request/BoardRequestDTO.java
src/main/java/com/gongkademy/domain/community/dto/response/BoardResponseDTO.java
src/main/java/com/gongkademy/domain/community/entity/board/Board.java
src/main/java/com/gongkademy/domain/community/repository/BoardRepository.java
src/main/java/com/gongkademy/domain/community/service/BoardService.java
src/main/java/com/gongkademy/domain/community/service/BoardServiceImpl.java
src/main/java/com/gongkademy/domain/member/entity/Member.java
src/test/java/com/gongkademy/domain/community/controller/BoardControllerTest.java
src/test/java/com/gongkademy/domain/community/service/BoardServiceImplTest.java

- resolve #32 
- LocalDateTime 기준 DESC 정령
- TOP3 게시물 GET

Feat : 공지사항 최신순 TOP3 (#32)

---

src/main/java/com/gongkademy/domain/community/controller/BoardController.java
src/main/java/com/gongkademy/domain/community/controller/CommentController.java
src/main/java/com/gongkademy/domain/community/dto/request/CommentRequestDTO.java
src/main/java/com/gongkademy/domain/community/dto/response/CommentResponseDTO.java
src/main/java/com/gongkademy/domain/community/entity/board/Board.java
src/main/java/com/gongkademy/domain/community/entity/comment/Comment.java
src/main/java/com/gongkademy/domain/community/repository/BoardRepository.java
src/main/java/com/gongkademy/domain/community/repository/CommentRepository.java
src/main/java/com/gongkademy/domain/community/service/BoardServiceImpl.java
src/main/java/com/gongkademy/domain/community/service/CommentService.java
src/main/java/com/gongkademy/domain/community/service/CommentServiceImpl.java
src/test/java/com/gongkademy/domain/community/service/BoardServiceImplTest.java

- resolve #34 
- 이번 PR에서 작업한 내용을 설명해주세요(이미지 첨부 가능)
1. 매직넘버 적용 설정
2. Board엔티티 상속 관계 SuperBuilder 설정
3. 댓글과 대댓글 CRD
4. 댓글 조회 쿼리 작성
5. 댓글 작성자와 사용자의 본인 확인 (인증에 따른 추가 확인 필요)

34 feat 댓글 기능 설정 및 리팩토링

---

src/main/java/com/gongkademy/domain/course/controller/PlayerController.java
src/main/java/com/gongkademy/domain/course/dto/request/PlayerRequestDTO.java
src/main/java/com/gongkademy/domain/course/dto/response/PlayerResponseDTO.java
src/main/java/com/gongkademy/domain/course/entity/Course.java
src/main/java/com/gongkademy/domain/course/entity/Lecture.java
src/main/java/com/gongkademy/domain/course/entity/RegistLecture.java
src/main/java/com/gongkademy/domain/course/repository/CourseRepository.java
src/main/java/com/gongkademy/domain/course/repository/LectureRepository.java
src/main/java/com/gongkademy/domain/course/repository/RegistCourseRepository.java
src/main/java/com/gongkademy/domain/course/repository/RegistLectureRepository.java
src/main/java/com/gongkademy/domain/course/service/PlayerService.java
src/main/java/com/gongkademy/domain/course/service/PlayerServiceImpl.java
src/test/java/com/gongkademy/service/PlayerServiceTest.java

- resolve #30 
- 강의 플레이어 관련 Controller 작업
- 강의 플레이어 관련 Service 작업
- 강의 플레이어 Repository 작업 (Regist Lecture, Lecture)

Feat: 강의 플레이어 관련 초기 작업

---

src/main/java/com/gongkademy/domain/community/dto/response/ImageResponseDto.java
src/main/java/com/gongkademy/domain/community/dto/response/QnaBoardResponseDto.java
src/main/java/com/gongkademy/domain/community/entity/board/QnaBoard.java
src/main/java/com/gongkademy/domain/community/service/BoardServiceImpl.java
src/main/java/com/gongkademy/domain/community/service/CommentServiceImpl.java
src/main/java/com/gongkademy/domain/community/service/QnaBoardServiceImpl.java

- resolve #44 
- QnaBoardDto에서 Builder 패턴을 적용
- Member 변경 사항을 코드에 반영하여 수정

Refactor : QnaBoardDto Builer 패턴 적용 및 Member 변경사항 반영

---

src/main/java/com/gongkademy/domain/community/controller/QuestionController.java
src/main/java/com/gongkademy/domain/community/repository/QnaBoardRepository.java
src/main/java/com/gongkademy/domain/community/service/PickServiceImpl.java
src/main/java/com/gongkademy/domain/community/service/QnaBoardService.java
src/main/java/com/gongkademy/domain/community/service/QnaBoardServiceImpl.java
src/test/java/com/gongkademy/domain/community/service/BoardServiceImplTest.java
src/test/java/com/gongkademy/repository/QnaBoardRepositoryTest.java

- resolve #46 
- 조회시 조회수 증가하도록 설정
- Pagenation 구현하여 한 페이지당 10개의 게시글 반환 및 criteria를 설정하여 정렬 기준 설정 가능

Feat: 조회수 및 Pagenation 구현

---

src/main/java/com/gongkademy/domain/community/entity/board/ImageBoard.java
src/main/java/com/gongkademy/domain/community/entity/board/QnaBoard.java
src/main/java/com/gongkademy/domain/community/service/QnaBoardServiceImpl.java
src/test/java/com/gongkademy/repository/QnaBoardRepositoryTest.java

- resolve #48 
- QnaBoard CRUD에 대한 테스트 코드 리팩토링 진행 (C/R/U/D 단위로 메서드 작성)
- QnaBoard 정렬 기준에 따른 전체조회 테스트 코드 작성

Test: 테스트 및 리팩토링 진행

---

src/main/java/com/gongkademy/domain/community/controller/BoardController.java
src/main/java/com/gongkademy/domain/community/controller/CommentController.java
src/main/java/com/gongkademy/domain/community/dto/response/BoardResponseDTO.java
src/main/java/com/gongkademy/domain/community/entity/board/Board.java
src/main/java/com/gongkademy/domain/community/entity/pick/Pick.java
src/main/java/com/gongkademy/domain/community/repository/PickRepository.java
src/main/java/com/gongkademy/domain/community/service/BoardService.java
src/main/java/com/gongkademy/domain/community/service/BoardServiceImpl.java

- resolve #49 
- 이번 PR에서 작업한 내용을 설명해주세요(이미지 첨부 가능)
1. API 명세서 URL 상태코드 일치화
2. Pick기능 추가, 의존성 주입
3. 게시판 좋아요 스크랩 기능 추가
4. 좋아요 / 스크랩한 게시글 리스트

49 refactor 명세서 일치화 작업

---

src/main/java/com/gongkademy/global/config/SecurityConfig.java
src/main/java/com/gongkademy/global/security/filter/JWTCheckFilter.java
src/main/java/com/gongkademy/global/security/handler/OAuth2LoginFailureHandler.java
src/main/java/com/gongkademy/global/security/handler/OAuth2LoginSuccessHandler.java

- #55 
-  기존 코드 JWT CheckFilter 리팩토링
-   JWT CheckFilter 리팩토링 에 따른 SecurityConfig 리팩토링
-  OAuth2 로그인이 성공하면 실행 될 OAuth2LoginSuccessHandler 구현
-  OAuth2 로그인이 실패하면 실행 될 OAuth2LoginFailureHandler 구현

Feat: JWT관련 Filter & Handler 구현

---

src/main/java/com/gongkademy/domain/member/dto/PrincipalDetails.java
src/main/java/com/gongkademy/domain/member/entity/Member.java
src/main/java/com/gongkademy/global/config/SecurityConfig.java
src/main/java/com/gongkademy/global/security/filter/JWTCheckFilter.java
src/main/java/com/gongkademy/global/security/handler/OAuth2LoginSuccessHandler.java
src/main/java/com/gongkademy/global/security/util/JWTUtil.java

-  #58 
- JWTCheckFilter 코드 리팩토링
- Token 검증 및 refreshToken 상태에 따른 accesToken 재발급 로직 수정
- JWTUtil 코드 리팩토링
- SecurityConfig 코드 리팩토링
- Redis DB 활용에 따른 Member가 refreshToken을 가지고있지 않게 수정
- PrincipalDetails 코드 리팩토링
- memberId 반환 메서드 추가

Refactor: Security 관련 코드 리팩토링

---

src/main/java/com/gongkademy/domain/course/controller/CourseController.java
src/main/java/com/gongkademy/domain/course/dto/request/CourseRequestDTO.java
src/main/java/com/gongkademy/domain/course/dto/response/CourseContentsResponseDTO.java
src/main/java/com/gongkademy/domain/course/dto/response/CourseResponseDTO.java
src/main/java/com/gongkademy/domain/course/entity/Course.java
src/main/java/com/gongkademy/domain/course/entity/CourseReview.java
src/main/java/com/gongkademy/domain/course/entity/Notice.java
src/main/java/com/gongkademy/domain/course/entity/RegistCourse.java
src/main/java/com/gongkademy/domain/course/entity/RegistLecture.java
src/main/java/com/gongkademy/domain/course/repository/LectureRepository.java
src/main/java/com/gongkademy/domain/course/repository/NoticeRepository.java
src/main/java/com/gongkademy/domain/course/repository/NoticeRepositoryImpl.java
src/main/java/com/gongkademy/domain/course/repository/RegistCourseRepository.java
src/main/java/com/gongkademy/domain/course/repository/RegistLectureRepository.java
src/main/java/com/gongkademy/domain/course/repository/ScrapRepository.java
src/main/java/com/gongkademy/domain/course/service/CourseService.java
src/main/java/com/gongkademy/domain/course/service/CourseServiceImpl.java
src/main/java/com/gongkademy/domain/member/entity/Member.java

- resolve #60 
- 전체 강좌 관련 기능 구현
- 강좌 상세 관련 기능 구현 (강의 파일/ 이미지/ 공지사항 페이지네이션 제외)

Feat : 강좌 상세 관련 기능 작업

---

src/main/java/com/gongkademy/domain/course/dto/response/CourseCommentResponseDTO.java
src/main/java/com/gongkademy/domain/course/entity/CourseComment.java
src/main/java/com/gongkademy/domain/course/service/CourseCommentServiceImpl.java

- resolve #66 
- **CourseComment Entity**
- LikeCount 메서드 명 변경
- **CourseComment Service**
- MemberRepository 주입 변경

Refactor: 강의 댓글 관련 코드 수정

---

src/main/java/com/gongkademy/domain/course/controller/PlayerController.java
src/main/java/com/gongkademy/domain/course/dto/request/PlayerRequestDTO.java
src/main/java/com/gongkademy/domain/course/dto/response/PlayerResponseDTO.java
src/main/java/com/gongkademy/domain/course/repository/RegistCourseRepository.java
src/main/java/com/gongkademy/domain/course/repository/RegistLectureRepository.java
src/main/java/com/gongkademy/domain/course/service/PlayerService.java
src/main/java/com/gongkademy/domain/course/service/PlayerServiceImpl.java

- resolve #65 
- 강의에 대한 최근 수강구간 조회 기능 추가
- 기존 강의 플레이어 관련 기능 수정
- dto 수정

Feat 강의 플레이어 관련 기능 추가

---

src/main/java/com/gongkademy/global/config/SecurityConfig.java

-  #62 
- SecurityFilterChain 메소드 작성
- CorsConfigurationSource 메소드 작성
- 기존 PasswordEncoder 삭제
- 기존 UserDetailService 메소드 삭제

Refactor: SecurityConfig 코드 리팩토링

---

src/main/java/com/gongkademy/domain/course/controller/CourseController.java
src/main/java/com/gongkademy/domain/course/dto/response/CourseResponseDTO.java
src/main/java/com/gongkademy/domain/course/repository/RegistCourseRepository.java
src/main/java/com/gongkademy/domain/course/service/CourseService.java
src/main/java/com/gongkademy/domain/course/service/CourseServiceImpl.java

- resolve #74 
- 마이페이지 수강 중 강좌 조회 기능 추가
- 마이페이지 수강완료 강좌 조회 기능 추가

Feat: 마이페이지 강좌 관련 기능 작업

---

src/main/java/com/gongkademy/domain/member/controller/MemberController.java
src/main/java/com/gongkademy/domain/member/entity/Member.java
src/main/java/com/gongkademy/domain/member/service/MemberService.java
src/main/java/com/gongkademy/domain/member/service/MemberServiceImpl.java
src/main/java/com/gongkademy/global/config/SecurityConfig.java
src/test/java/com/gongkademy/repository/MemberRepositoryTest.java

- resolve #72 
-  MemberController Http 요청 메소드 구현
- Controller 변경 사항에 따라 SecurityConfig 코드 리팩토링
- MemberService 코드 리팩토링
- MemberServiceImpl 코드 리팩토링
- MemberRepositoryTest 코드 전체 주석처리(추후 리팩토링 예정)

72 feat membercontroller 구현

---

src/main/java/com/gongkademy/domain/member/service/MemberServiceImpl.java

- #63 
- MemberServiceImpl 내 refreshToken 관련 로직 추가
- joinMember()에 회원가입 시 refreshToken을 발급하도록 수정했습니다.

Refactor: MemberServiceImpl 내 refreshToken 관련 로직 추가

---

src/main/java/com/gongkademy/domain/community/controller/QuestionController.java
src/main/java/com/gongkademy/domain/community/service/QnaBoardService.java
src/main/java/com/gongkademy/domain/community/service/QnaBoardServiceImpl.java

- resolve #86 
-  QnaBoard 좋아요 및 스크랩 메서드 작성하였습니다.

Feat: 좋아요 및 스크랩 메서드 작성

---

src/main/java/com/gongkademy/domain/community/controller/ConsultingController.java
src/main/java/com/gongkademy/domain/community/controller/QuestionController.java
src/main/java/com/gongkademy/domain/community/dto/request/QnaBoardRequestDTO.java
src/main/java/com/gongkademy/domain/community/dto/response/QnaBoardResponseDTO.java
src/main/java/com/gongkademy/domain/community/entity/board/QnaBoard.java
src/main/java/com/gongkademy/domain/community/service/ConsultingBoardService.java
src/main/java/com/gongkademy/domain/community/service/ConsultingBoardServiceImpl.java
src/main/java/com/gongkademy/domain/community/service/QnaBoardService.java
src/main/java/com/gongkademy/domain/community/service/QnaBoardServiceImpl.java
src/test/java/com/gongkademy/repository/QnaBoardRepositoryTest.java

- resolve #90 
- Consulting 게시판 (Controller, Service, Repo) 코드 작성
- Notice 게시판과 유사하여 기존 작업해 둔 메서드를 최대한 활용

Feat: Consulting 게시판 (Controller, Service, Repo) 코드 작성

---

src/main/java/com/gongkademy/domain/community/controller/BoardController.java
src/main/java/com/gongkademy/domain/community/controller/CommentController.java
src/main/java/com/gongkademy/domain/community/dto/response/CommentResponseDTO.java
src/main/java/com/gongkademy/domain/community/service/CommentService.java
src/main/java/com/gongkademy/domain/community/service/CommentServiceImpl.java
src/main/java/com/gongkademy/global/exception/ErrorCode.java
src/test/java/com/gongkademy/domain/community/service/CommentServiceImplTest.java

- resolve #84 
- 권한별 게시글 / 댓글 수정 / 삭제 기능

84 feat 유저별 기능

---

src/main/java/com/gongkademy/domain/course/controller/CourseController.java
src/main/java/com/gongkademy/domain/course/dto/request/CourseLikeRequestDTO.java
src/main/java/com/gongkademy/domain/course/dto/response/CourseLikeResponseDTO.java
src/main/java/com/gongkademy/domain/course/entity/CourseComment.java
src/main/java/com/gongkademy/domain/course/entity/CourseLike.java
src/main/java/com/gongkademy/domain/course/entity/CourseLikeCateg.java
src/main/java/com/gongkademy/domain/course/entity/CourseReview.java
src/main/java/com/gongkademy/domain/course/entity/Notice.java
src/main/java/com/gongkademy/domain/course/repository/CourseLikeRepository.java
src/main/java/com/gongkademy/domain/course/service/CourseService.java
src/main/java/com/gongkademy/domain/course/service/CourseServiceImpl.java
src/main/java/com/gongkademy/domain/member/entity/Member.java

- resolve #79 
**- CourseLikeEntity 구현**
**- CourseLikeDTO 구현
- CourseController**
- CourseLike Create 메서드 구현
- CourseLike Delete 메서드 구현
**- CourseService**
- CourseLike convertToDTO 작성
- CourseLike convertToEntity 작성
- CourseLike 존재 여부 확인 및 좋아요 등록/삭제 메서드 구현
**- CourseLikeRepository**
- ID 조합으로 DB 존재 여부 확인 쿼리 작성

Feat: Course 좋아요 기능 코드 구현

---

src/main/java/com/gongkademy/domain/course/dto/response/PlayerResponseDTO.java
src/main/java/com/gongkademy/domain/course/entity/RegistCourse.java
src/main/java/com/gongkademy/domain/course/entity/RegistLecture.java
src/main/java/com/gongkademy/domain/course/service/PlayerServiceImpl.java

- resolve #80 
- 강의 수강 진행률 저장 로직 추가
- 플레이어 응답 dto 수정

Feat: 강의 플레이어 관련 기능 추가

---

src/main/java/com/gongkademy/domain/course/controller/CourseCommentController.java
src/main/java/com/gongkademy/domain/course/controller/CourseController.java
src/main/java/com/gongkademy/domain/course/repository/CourseCommentRepository.java
src/main/java/com/gongkademy/domain/course/repository/CourseLikeRepository.java
src/main/java/com/gongkademy/domain/course/service/CourseCommentServiceImpl.java
src/main/java/com/gongkademy/domain/course/service/CourseService.java
src/main/java/com/gongkademy/domain/course/service/CourseServiceImpl.java

- resolve #94 
- 좋아요 갯수 UP&Down 코드 추가
- CourseCommentController Mapping 메서드 올바르게 수정
- CourseCommentRepository 메서드명 변경

Refactor: Course 리팩토링

---

src/main/java/com/gongkademy/domain/course/controller/CourseCommentController.java
src/main/java/com/gongkademy/domain/course/controller/CourseController.java
src/main/java/com/gongkademy/domain/course/controller/CourseReviewController.java
src/main/java/com/gongkademy/domain/course/controller/PlayerController.java
src/main/java/com/gongkademy/domain/course/entity/Scrap.java
src/main/java/com/gongkademy/domain/course/repository/CourseLikeRepository.java
src/main/java/com/gongkademy/domain/course/repository/ScrapRepository.java
src/main/java/com/gongkademy/domain/course/service/CourseCommentService.java
src/main/java/com/gongkademy/domain/course/service/CourseCommentServiceImpl.java
src/main/java/com/gongkademy/domain/course/service/CourseReviewService.java
src/main/java/com/gongkademy/domain/course/service/CourseReviewServiceImpl.java
src/main/java/com/gongkademy/domain/course/service/CourseService.java
src/main/java/com/gongkademy/domain/course/service/CourseServiceImpl.java
src/main/java/com/gongkademy/domain/course/service/PlayerService.java
src/main/java/com/gongkademy/domain/course/service/PlayerServiceImpl.java

- resolve #97 
- 댓글 관련 authentication 추가
- 강좌 관련 authentication 추가
- 강의 플레이어 관련 authentication 추가

Refactor: course 도메인 authentication 추가

---

src/main/java/com/gongkademy/domain/course/controller/CourseController.java
src/main/java/com/gongkademy/domain/course/repository/CourseLikeRepository.java
src/main/java/com/gongkademy/domain/course/service/CourseServiceImpl.java

- resolve #101 
- CourseLikeRepo 메서드명 수정
- CourseController 상에 완성되지 않은 메서드 주석 처리 
(주석 처리보다는 @PathVariable 추가해서 작성해 놓아야 Mapping이 될 듯 싶습니다.)

Fix: CourseLikeRepo 메서드명 수정

---

src/main/java/com/gongkademy/domain/community/controller/CommentController.java
src/main/java/com/gongkademy/domain/community/service/CommentService.java
src/main/java/com/gongkademy/domain/community/service/CommentServiceImpl.java

- resolve #103 
- CurrentMemberId 불필요 메서드 제거

REFACTOR : 불필요 파라미터 제거

---

src/main/java/com/gongkademy/domain/course/dto/request/CourseCommentRequestDTO.java
src/main/java/com/gongkademy/domain/course/dto/response/CourseCommentResponseDTO.java
src/main/java/com/gongkademy/domain/course/dto/response/CourseReviewResponseDTO.java
src/main/java/com/gongkademy/domain/course/entity/Course.java
src/main/java/com/gongkademy/domain/course/entity/CourseComment.java
src/main/java/com/gongkademy/domain/course/entity/CourseReview.java
src/main/java/com/gongkademy/domain/course/entity/Lecture.java
src/main/java/com/gongkademy/domain/course/entity/Notice.java
src/main/java/com/gongkademy/domain/course/entity/RegistCourse.java
src/main/java/com/gongkademy/domain/course/service/CourseCommentServiceImpl.java
src/main/java/com/gongkademy/domain/course/service/CourseReviewServiceImpl.java
src/main/java/com/gongkademy/domain/course/service/CourseServiceImpl.java
src/main/java/com/gongkademy/domain/member/entity/Member.java

- resolve #100 
- 강좌 도메인 엔티티 (cascade, 비즈니스로직 수정) 수정

Refactor: 강의 도메인 엔티티 수정

---

src/main/java/com/gongkademy/domain/community/controller/BoardController.java
src/main/java/com/gongkademy/domain/community/controller/CommentController.java
src/main/java/com/gongkademy/domain/community/dto/response/BoardResponseDTO.java
src/main/java/com/gongkademy/domain/community/entity/board/Board.java
src/main/java/com/gongkademy/domain/community/service/BoardServiceImpl.java
src/main/java/com/gongkademy/domain/community/service/CommentService.java

- resolve #108 
- 공지사항 상세 조회 and 댓글 조회 API 합체

Refactor : 상세조회 시 댓글불러오기

---

src/main/java/com/gongkademy/domain/community/dto/response/BoardResponseDTO.java

- resolve #108 
- * Refactor : 상세조회 시 댓글불러오기
* Refactor : Board Entity DTO 수정

108 refactor 공지사항 기능 수정 (#111)

---

src/main/java/com/gongkademy/domain/community/entity/board/Board.java

- resolve #114 
- Fix : Entity DTO 에러 수정

Fix : Entity DTO 에러 수정

---

src/main/java/com/gongkademy/domain/community/controller/ConsultingController.java
src/main/java/com/gongkademy/domain/community/controller/QuestionController.java
src/main/java/com/gongkademy/domain/community/repository/BoardRepository.java
src/main/java/com/gongkademy/domain/community/repository/QnaBoardRepository.java
src/main/java/com/gongkademy/domain/community/service/ConsultingBoardService.java
src/main/java/com/gongkademy/domain/community/service/ConsultingBoardServiceImpl.java
src/main/java/com/gongkademy/domain/community/service/QnaBoardService.java
src/main/java/com/gongkademy/domain/community/service/QnaBoardServiceImpl.java

- resolve #109 
- 키워드를 포함한 검색 기능 구현
- Qna, Consulting Controller API 리팩토링 진행 (Mapping url 변경)
- Qna, Consulting Service 리팩토링 진행 (Transactional 반영)

Feat: 키워드 기반 검색 기능 추가

---

src/main/java/com/gongkademy/domain/member/dto/PrincipalDetails.java
src/main/java/com/gongkademy/global/security/handler/OAuth2LoginSuccessHandler.java

- #122 
- PrincipalDetails
- 리스트로 두 겹 감싸져 있는 것 수정
- OAuth2LoginSuccessHandler
- if문 조건 수정 (key(ex. ROLE_USER) 와 (ex.list [GUEST, USER])를 자꾸 비교하고 있었음)

[Fix] Member RoleList 오류 수정

---

src/main/java/com/gongkademy/domain/notification/controller/NotificationController.java
src/main/java/com/gongkademy/domain/notification/dto/NotificationDTO.java
src/main/java/com/gongkademy/domain/notification/entity/Notification.java
src/main/java/com/gongkademy/domain/notification/repository/EmitterRepository.java
src/main/java/com/gongkademy/domain/notification/repository/EmitterRepositoryImpl.java
src/main/java/com/gongkademy/domain/notification/repository/NotificationRepository.java
src/main/java/com/gongkademy/domain/notification/service/NotificationService.java

- #127 
- Notification 구현 방법 SSE / webSocket 중에 **SSE**로 확정
- Notification 관련 초기 세팅
- Notification 관련 **SSE 구현요소 emitter** 관련 초기 세팅

127 feat 알림 관련 세팅

---

src/main/java/com/gongkademy/domain/member/dto/MemberInfoDTO.java
src/main/java/com/gongkademy/domain/member/entity/Member.java
src/main/java/com/gongkademy/domain/member/service/MemberService.java

- resolve #이슈번호
-  MemberInfoDTO createTime 필드명 수정
- Member Entity createTime 필드 추가
- MemerService entityToMemberInfoDTO() 수정

Refactor: member createdate 관련 수정

---

src/main/java/com/gongkademy/domain/course/controller/CourseCommentController.java
src/main/java/com/gongkademy/domain/course/controller/CourseReviewController.java
src/main/java/com/gongkademy/domain/course/controller/PlayerController.java
src/main/java/com/gongkademy/domain/course/entity/Course.java
src/main/java/com/gongkademy/domain/course/repository/CourseReviewRepository.java
src/main/java/com/gongkademy/domain/course/service/CourseCommentService.java
src/main/java/com/gongkademy/domain/course/service/CourseCommentServiceImpl.java
src/main/java/com/gongkademy/domain/course/service/CourseReviewService.java
src/main/java/com/gongkademy/domain/course/service/CourseReviewServiceImpl.java
src/main/java/com/gongkademy/domain/course/service/CourseServiceImpl.java
src/main/java/com/gongkademy/domain/course/service/PlayerService.java
src/main/java/com/gongkademy/domain/course/service/PlayerServiceImpl.java

- resolve #136 
- 강의 도메인 내 삽입, 삭제, 수정 메서드에 대한 사용자 권한 확인 코드 추가
- 컨트롤러 주석 작성

Feat: 강의 도메인 접근 권한 설정

---

src/main/java/com/gongkademy/domain/course/repository/PreCourseRepository.java
src/main/java/com/gongkademy/domain/course/service/CourseServiceImpl.java

- resolve #141 
- 선수과목 repo 오류 해결

Fix:선수과목 repo 오류 해결

---

src/main/java/com/gongkademy/domain/community/controller/ConsultingController.java
src/main/java/com/gongkademy/domain/community/controller/QuestionController.java
src/main/java/com/gongkademy/domain/community/dto/request/ConsultingBoardRequestDTO.java
src/main/java/com/gongkademy/domain/community/dto/response/ConsultingBoardResponseDTO.java
src/main/java/com/gongkademy/domain/community/repository/PickRepository.java
src/main/java/com/gongkademy/domain/community/service/ConsultingBoardService.java
src/main/java/com/gongkademy/domain/community/service/ConsultingBoardServiceImpl.java
src/main/java/com/gongkademy/domain/community/service/QnaBoardService.java
src/main/java/com/gongkademy/domain/community/service/QnaBoardServiceImpl.java

- resolve #143 
- 게시글 전체 조회 시 로그인 유저의 좋아요, 스크랩 여부를 확인할 수 있는 기능을 추가

 Feat: 좋아요 스크랩 여부 확인

---

src/main/java/com/gongkademy/domain/community/controller/BoardController.java
src/main/java/com/gongkademy/domain/community/dto/response/BoardResponseDTO.java
src/main/java/com/gongkademy/domain/community/service/BoardService.java
src/main/java/com/gongkademy/domain/community/service/BoardServiceImpl.java
src/test/java/com/gongkademy/domain/community/controller/BoardControllerTest.java

- resolve #126 
- 좋아요 스크랩 여부 확인
- 1개 상세보기와 리스트로 볼 시 좋아요 스크랩 여부 확인
- 비로그인 시 상세보기와 리스트 보기 기능 추가

126 feat 좋아요 스크랩여부 확인

---

src/main/java/com/gongkademy/global/security/handler/OAuth2LoginSuccessHandler.java

-  #146 
- 이번 PR에서 작업한 내용을 설명해주세요(이미지 첨부 가능)
- **Auth2LoginSuccessHandler 에서 로그인 성공 시, 멤버의 권한을 판단해 MainUrl, 혹은 SignUpUrl 로 Redirect시키는 과정에서 Response가 초기화 되어서 Front단에서 accessToken을 가져올 수 없었음.**
- --
- **해결방법**
- accessToken을 Cookie에 저장시켜(유효시간 1시간) Front에서 꺼내쓸 수 있도록 함.
---

Fix: OAuth2LoginSuccessHandler accessToken 관련 redirect 오류 수정

---

src/main/java/com/gongkademy/global/security/util/JWTUtil.java

- #125 
- JWTUtil isTokenValid() 수정
- ExpiredException 걸리는 것 수정
- JWTUtil isExpired() 수정
- 여기에서 ExpiredException 따로 처리함
- JWTUtil extractMemberId() 수정
- access token 만료 시 memberId(access token 안의)로 refresh token을 가져와야 하는데, 
수정 전은 extractMemberId() 메서드 실행 시 ExpiredException에 걸리므로
만료된 access token 에서 memberId를 가져올 수 있도록 수정

Refactor: JWTUtil token expired 관련 수정
